name: License Header Check

on: [ pull_request ]

jobs:
  compliant:
    runs-on: ubuntu-latest
    steps:
      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
        with:
          mode: fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Changes
        uses: EndBug/add-and-commit@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
